[package]
name = "project_euler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
function_name = "0.3.0"
itertools = "0.12.1"
num-bigint = "0.4.4"
num-traits = "0.2.18"
